# Generated by Django 4.2.6 on 2023-12-18 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_carro_placa'),
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=1000)),
                ('data_inicio', models.DateField()),
                ('data_entrega', models.DateField(null=True)),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.carro')),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipe.equipe')),
            ],
        ),
    ]
