# Generated by Django 4.2.6 on 2023-12-19 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='pecas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.pecas'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.servicos'),
        ),
    ]
