# Generated by Django 4.2.6 on 2023-12-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_requisicao_pecas_requisicao_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
